# Generated by Django 3.1 on 2021-05-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210504_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pos',
            field=models.IntegerField(default=0),
        ),
    ]
