# Generated by Django 3.2.2 on 2021-07-12 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='picture_back',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='picture_front',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='state1',
            field=models.CharField(max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='state2',
            field=models.CharField(max_length=65535, null=True),
        ),
    ]
