# Generated by Django 3.2.2 on 2021-07-14 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210714_2315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
