# Generated by Django 3.2.2 on 2021-07-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20, verbose_name='颜色')),
                ('price', models.FloatField(verbose_name='价格')),
                ('digital', models.SmallIntegerField(verbose_name='数字大小')),
                ('dingzhiproduct', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imgname', models.FileField(upload_to='img/')),
            ],
        ),
    ]
