# Generated by Django 3.2.2 on 2021-07-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_draw_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state1',
            field=models.CharField(max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='state2',
            field=models.CharField(max_length=65535, null=True),
        ),
    ]
