# Generated by Django 3.2.2 on 2021-07-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210716_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='jsondata',
            field=models.CharField(max_length=65535, null=True),
        ),
    ]
