# Generated by Django 3.2.2 on 2021-07-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_jsondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
