# Generated by Django 3.1.2 on 2021-08-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20210817_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='combo',
            field=models.CharField(max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='totalprice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
