# Generated by Django 3.1.2 on 2021-08-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20210822_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='totalprice',
        ),
    ]
