# Generated by Django 3.1.2 on 2021-08-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20210823_1203'),
    ]

    operations = [
    ]
