# Generated by Django 3.2.2 on 2021-09-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20210823_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='gs',
            field=models.CharField(max_length=200, null=True, verbose_name='公司'),
        ),
    ]
