# Generated by Django 3.2.2 on 2021-09-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_shippingaddress_gs'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='userorderid',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='userorderid',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('userorderid', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('status', models.IntegerField(default=1, null=True, verbose_name='订单状态；0完成；1已付款；2已发货')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('addressid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.shippingaddress', verbose_name='地址id')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer', verbose_name='客户id')),
            ],
        ),
    ]
