# Generated by Django 3.2.2 on 2021-09-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20210909_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='choosepk',
            field=models.CharField(max_length=65535, null=True),
        ),
    ]
