# Generated by Django 3.2.2 on 2021-09-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20210915_1546'),
    ]

    operations = [

        migrations.AddField(
            model_name='order',
            name='delstatus',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
