# Generated by Django 3.2.2 on 2021-09-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20210918_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='shui',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userorder',
            name='yunfei',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
