# Generated by Django 3.2.2 on 2021-10-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20210925_1529'),
    ]

    operations = [
    ]
