# Generated by Django 3.2.2 on 2021-10-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_merge_0029_auto_20210925_1529_0029_auto_20210926_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='youkeorder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver', models.CharField(max_length=65535)),
                ('get_way', models.CharField(max_length=65535)),
                ('phone', models.CharField(max_length=65535)),
                ('email', models.CharField(max_length=65535)),
                ('company', models.CharField(max_length=65535)),
                ('totalprices', models.FloatField()),
                ('yunfei', models.FloatField()),
                ('amount', models.FloatField()),
                ('shui', models.FloatField()),
                ('nation', models.CharField(max_length=65535)),
                ('province', models.CharField(max_length=65535)),
                ('city', models.CharField(max_length=65535)),
                ('postcode', models.CharField(max_length=65535)),
                ('addinfo', models.CharField(max_length=65535)),
                ('items', models.IntegerField(default=0)),
                ('itemsjson', models.CharField(max_length=65535)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
